import Header from "./components/Header";
import "./global.css";
import Providers from "./Providers";
import {Toaster} from "sonner"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Toaster position="top-center" richColors />
        </Providers>
      </body>
    </html>
  );
}
